### ISSUE TITLE
Switch bak to rust-crypto

### ISSUE THREAD

**Issue by nathansizemore** [Keats/rust-jwt#18]
No longer can compile 

```/ring-3628119f6179288e/out/obj/crypto/aes/asm/aes-x86_64.S:3:1: error: unknown directive
.type _x86_64_AES_encrypt,@function
^```

ring currently requires a lot of host specific build tools, which now makes this package unable to cross compile. At least keep this able to cross compile until ring gets it's build chain setup better.

**Comment by nathansizemore** [comment]
[Associated ring issue](https://github.com/briansmith/ring/issues/281)

**Comment by Keats** [comment]
aw sorry about that, i'll add a feature to use rust-crypto instead of ring

**Comment by nathansizemore** [comment]
No biggie, I've got it pegged at the needed version in the meantime. I'd imagine once they get their build chain in a more complete state, things will be fine.

**Comment by Keats** [comment]
Did you manage to cross-compile in the nd?

**Comment by nathansizemore** [comment]
Whoops, I forgot about this issue, sorry. Yeah, so it wasn't a fault of this, it was just a fault of me not having the proper toolchain setup. I've figured out that it is more or less not worth the effort to cross compile to Linux from macOS, and just bit the bullet and started to use a VM.
