### ISSUE TITLE
`decode` doesn't take arbitrary bytes as input

### ISSUE THREAD

**Issue by untitaker** [Keats/rust-jwt#2]
I have a key that is not valid UTF-8. Currently it's possible to encode, but not decode using such a key.

I've been working on a PR that makes `decode` take `AsRef<[u8]>` (like `encode`), but on the way I've found that this breaks `decode::<Claims>(..)` usage because of additional type parameters. The other options are:

* `decode<T: Part>(token: &str, secret: &AsRef<[u8]>, algorithm: ...) -> Result<T, ...>`, no idea why this works???

* Just advise users to use different forms of typehinting if possible, and only use `decode::<Claims, _>` if necessary.

**Comment by Keats** [comment]
If option 1 works on stable/beta/nightly (ie passes travis), I'd be tempted to go that way. If you do a PR could you add tests for non-valid UTF-8 keys as well please?

**Comment by untitaker** [comment]
Note that according to IRC the first option involves virtual dispatch. Not sure if that's problematic to you.

Before I take a look at it I'll ask a bit around if this is even intended behavior.

**Comment by untitaker** [comment]
From IRC:

>@kimundi: All I can say is that that should not work, and if it does then you are doing something different than when you used the generic version

**Comment by untitaker** [comment]
What about having `secret: &[u8]`? Calling `as_ref` on the caller-side seems easy enough:

    decode(token, "foobar".as_ref(), ...)

**Comment by Keats** [comment]
If it should not work, is it worth trying to raise an issue in Rust itself?

For the invalid UTF-8 issue, is that a key you are generating yourself? I expect most people to use a valid string (or base64 it if not) so i'd prefer not making it more annoying for 99% of the users.

If you can add failing tests i'll have a look tomorrow as well

**Comment by untitaker** [comment]
>For the invalid UTF-8 issue, is that a key you are generating yourself?

Yes, generated myself, but it doesn't matter. I'd expect arbitrary bytes to work since the RFC doesn't mention any restriction.
