### ISSUE TITLE
How can I best contribute?

### ISSUE THREAD

**Issue by mike-engel** [Keats/rust-jwt#25]
Hey there! First off, thanks for making what's shaping up to be a great crate!

I'm new to Rust, and getting my toes wet by building a [jwt cli tool](https://github.com/mike-engel/jwt-cli). I'd love to contribute back to this project, but I'm not sure where I would be most helpful. Docs? Some easy feature? I'm not sure what you have in progress already so let me know if I can help.

**Comment by Keats** [comment]
Thanks for the kind words!

Regarding stuff in progress: https://github.com/Keats/rust-jwt/pull/23 is an ongoing re-write, currently waiting for a Ring PR + new release to finish RSA support.

I need some help coming up with ideas on how to handle validation (https://github.com/Keats/rust-jwt/issues/22) and there some interesting API ideas on https://github.com/Keats/rust-jwt/issues/13 

I think the best help would be to try the `v2` branch once it's a bit more stable to make sure the API etc makes sense, is easy to use and cover most usecases

**Comment by mike-engel** [comment]
Sweet, thanks! I'll take a look at those issues and subscribe to the v2 pr.

**Comment by Keats** [comment]
v2 is on crates.io, thanks a lot for your help!

**Comment by mike-engel** [comment]
Happy to help! Thanks for making it in the first place!
