### ISSUE TITLE
Header::from_base64 doesn't accept/"just discard" extra fields or differently ordered JSON

### ISSUE THREAD

**Issue by untitaker** [Keats/rust-jwt#4]
This header works:

    {
      "alg": "HS256",
      "typ": "JWT"
    }

This doesn't:

    {
      "typ": "JWT",
      "alg": "HS256"
    }

**Comment by untitaker** [comment]
Also the latter is used in some `should_panic` tests, which may cause them to panic (as expected), but for a unexpected reason.

**Comment by Keats** [comment]
Ah yes, encrypted json was hardcoded for the header in a previous PR. Didn't think about the order

**Comment by Keats** [comment]
Before i do anything, does the title mean you want to have header fields other than `typ` and `alg` like `kid`?
That's not something I need right now but would accept a PR.

If it's only the order, i'll do that tonight/tomorrow

**Comment by untitaker** [comment]
It's just something I noticed while generating testcases for #3 using http://jwt.io. Not something I actually need. Since in my case I am the only one who generates and parses tokens, I can easily keep the fields in a certain order.

**Comment by Keats** [comment]
The order is definitely a bug, i'll fix it today.

**Comment by untitaker** [comment]
For full RFC compliance more headers would have to be accounted for.

**Comment by Keats** [comment]
Yeah I know, just not a priority for me as I only use jwt generated by me.
I guess we will add it when someones needs to handle jwt containing other fields like the ones from google cloud.

**Comment by untitaker** [comment]
I've created #5 to fix that bug. While it currently doesn't allow inspection of any of those weird header values, I think dropping them is a reasonable way to deal with them for now.
