### ISSUE TITLE
Split out JWS implementation

### ISSUE THREAD

**Issue by emosenkis** [Keats/rust-jwt#9]
I'm thinking of trying to implement the ACME protocol (e.g. LetsEncrypt), which requires JWS. Would you consider splitting that part of the functionality into a separate library or at least making the appropriate parts public?

**Comment by Keats** [comment]
I don't want to split the package, can you do a PR making what you need public?

**Comment by Keats** [comment]
@emosenkis ping

**Comment by emosenkis** [comment]
This is for a side project, so I may not get to it for a long time. If and when I get to it, I'll send you a pull request. Feel free to close this issue if you prefer.
